name: flutter_app
description: A secure Flutter mobile application with license protection
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # مكتبات الأمان والحماية
  shared_preferences: 2.5.3     # تخزين بيانات الترخيص
  device_info_plus: 10.1.2      # الحصول على معلومات الجهاز
  crypto: 3.0.6                 # التشفير وإنشاء البصمات
         
           
  flutter_secure_storage: 9.0.0      # ← أضف هذا
  path_provider: 2.1.1              # ← أضف هذا
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
